# This GitHub Actions workflow automates the continuous integration process.
# It triggers on push or pull request events to the main branch, sets up a Python environment,
# installs dependencies, and runs tests using pytest.

# Name of the GitHub Actions workflow
name: CI Workflow

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies required for testing
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    # Step 4: Run the tests using pytest
    - name: Run tests
      run: |
        pytest _test.py